defmodule HllConditionalActionsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hll_conditional_actions

  # The session holds the signed in user's id and nothing else. It is signed,
  # so the browser can read it but cannot forge it.
  #
  #   * `http_only` keeps it away from scripts, so an injected script cannot
  #     read somebody's session out of `document.cookie`
  #   * `secure` refuses to send it over plain HTTP, which matters behind a
  #     proxy that terminates TLS: without it the cookie would travel in clear
  #     on any request that reached the app over http
  #   * `max_age` ends an abandoned session on a shared machine after a week
  #
  # `secure` is off outside production only because dev and test are served
  # over http, where a secure cookie is never sent at all.
  @secure_cookies Application.compile_env(:hll_conditional_actions, :secure_cookies, false)

  @session_options [
    store: :cookie,
    key: "_hll_conditional_actions_key",
    signing_salt: "Ej99+OaA",
    same_site: "Lax",
    http_only: true,
    secure: @secure_cookies,
    max_age: 60 * 60 * 24 * 7
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hll_conditional_actions,
    gzip: not code_reloading?,
    only: HllConditionalActionsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hll_conditional_actions
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HllConditionalActionsWeb.Router
end
