defmodule HllConditionalActionsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hll_conditional_actions

  # The session holds the signed in user's id and nothing else. It is signed,
  # so the browser can read it but cannot forge it.
  #
  #   * `http_only` keeps it away from scripts, so an injected script cannot
  #     read somebody's session out of `document.cookie`
  #   * `secure` refuses to send it over plain HTTP, which matters behind a
  #     proxy that terminates TLS: without it the cookie would travel in clear
  #     on any request that reached the app over http
  #   * `max_age` ends an abandoned session on a shared machine after a week
  #
  # `secure` is decided at *boot*, not at compile time, because the same
  # release runs two ways: behind the Caddy in `compose.prod.yaml`, where
  # everything is TLS and the flag must be on, and published directly on its
  # own port over plain HTTP, where a secure cookie would never be sent at all
  # and nobody could sign in. `config/runtime.exs` sets it from BEHIND_PROXY.
  @session_options [
    store: :cookie,
    key: "_hll_conditional_actions_key",
    signing_salt: "Ej99+OaA",
    same_site: "Lax",
    http_only: true,
    max_age: 60 * 60 * 24 * 7
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hll_conditional_actions,
    gzip: not code_reloading?,
    only: HllConditionalActionsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hll_conditional_actions
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  # Phoenix's own `force_ssl` is a *compile time* endpoint key: setting it in
  # runtime.exs makes the release refuse to boot with a "different value at
  # runtime" error. Doing the redirect here instead is what lets one image both
  # sit behind Caddy and be published directly over plain HTTP, where
  # redirecting to https would loop forever.
  plug :force_https

  plug :session

  defp force_https(conn, _opts) do
    if Application.get_env(:hll_conditional_actions, :force_https, false) do
      Plug.SSL.call(conn, ssl_options())
    else
      conn
    end
  end

  defp ssl_options do
    cached(:ssl, fn ->
      Plug.SSL.init(
        rewrite_on: [:x_forwarded_proto],
        # Plug.SSL's `exclude` is a list of *hosts*. A container healthcheck or
        # a probe on the loopback address is not something to redirect.
        exclude: ["localhost", "127.0.0.1"]
      )
    end)
  end

  # Built once on the first request and kept in :persistent_term, because the
  # endpoint's pipeline is compiled and cannot read application config for us.
  defp session(conn, _opts), do: Plug.Session.call(conn, session_plug_options())

  defp session_plug_options do
    cached(:session, fn ->
      Plug.Session.init(
        Keyword.put(
          @session_options,
          :secure,
          Application.get_env(:hll_conditional_actions, :secure_cookies, false)
        )
      )
    end)
  end

  # Built on first use and kept, because the endpoint's pipeline is compiled
  # and cannot read application config on our behalf.
  defp cached(key, build) do
    case :persistent_term.get({__MODULE__, key}, nil) do
      nil ->
        value = build.()
        :persistent_term.put({__MODULE__, key}, value)
        value

      value ->
        value
    end
  end

  plug HllConditionalActionsWeb.Router
end
