import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hll_conditional_actions, HllConditionalActionsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# `force_ssl` and the secure cookie flag are decided at boot, in
# config/runtime.exs, from BEHIND_PROXY — the same release runs behind the
# Caddy in compose.yaml and, when somebody prefers it, published directly
# on its own port over plain HTTP.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
