import Config

# Read at compile time by the endpoint's session options and by the plug that
# decides whether `X-Forwarded-For` can be believed. Both are true here and
# nowhere else: production is the only environment served over TLS, and the
# only one that runs behind the Caddy in `compose.prod.yaml`.
config :hll_conditional_actions,
  secure_cookies: true,
  trust_proxy_headers: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hll_conditional_actions, HllConditionalActionsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :hll_conditional_actions, HllConditionalActionsWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Container healthchecks hit the app over plain HTTP from inside the
      # network, where a redirect to https would look like a failure.
      paths: ["/health", "/health/ready"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
